Revert "Techpack: audio: ASoC: tfa98xx: fix enum comparison warning"
Reason: This gives erros on AOSP clang such as:

../../../../../../kernel/lenovo/sm8150/techpack/audio/asoc/codecs/tfa9874/tfa98xx.c:209:8: error: implicit conversion from enumeration type 'enum Tfa98xx_Error' to different enumeration type 'enum tfa_error' [-Werror,-Wenum-conversion]
        err = tfa_dev_mtp_set(tfa, TFA_MTP_EX, 0);
            ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This reverts commit 8d65f4a5aecb9d5fd1b22f1c7dceb524a7a82c31.